
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: myfirst-container
    image: nginx:latest
    ports:
    - containerPort: 80

apiVersion: v1
kind: Pod
metadata: 
  name: firstpod
  labels:
    env: prod
    name: raja
spec: 
  containers: 
  - name: first
    image: nginx
    env:
      - name: myname
        value: raja
      - name: City
        value: Hyderabad
  - name: second 
    image: nginx