apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc

spec:
  replicas: 5
  selector:           
    app: nginx          
  template:
    metadata: 
      name: firstpod
      labels:
        app: nginx 
    spec: 
      containers: 
      - name: first-container 
        image: nginx
        ports:
          - containerPort: 80