apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc
  labels:
    appname: testapp

spec:
  replicas: 5
  selector:           
    env: prod          
  template:
    metadata: 
      name: firstpod
      labels:
        env: prod
    spec: 
      containers: 
      - name: first-container 
        image: nginx
        env:
          - name: raja