apiVersion: v1
kind: ReplicationController
metadata:
  name: firstrc
  labels:
    appname: testapp

spec:                              
  replicas: 5
  template:
    metadata: 
      name: firstpod
      labels:
        env: prod
    spec:                         
      containers: 
      - name: firstcontainer 
        image: nginx
        env:
          - name: raja
