apiVersion: v1
kind: Service
metadata:
  name: firstservice
  labels:
     app: nginx
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      protcol: Tcp
      targetPort: 80
  selector:
    app: nginx
    type: app